py_test(
    name = "pre_prompt_templates_testcase",
    srcs = ["pre_prompt_templates_testcase.py"],
    deps = ["//agents/ada:slackbot"],
    data = ["expected_pre_prompts/persona", "expected_pre_prompts/footer", "expected_pre_prompts/personalized"],
)
