py_binary(
    name = "console",
    srcs = [
        "console.py",
        "prompt_templates/rfp_copilot_template.py",
    ],
)

py_library(
    name = "console_prompt_templates",
    srcs = [
        "prompt_templates/rfp_copilot_template.py",
    ],
)
